### ISSUE TITLE
[kwin-mv-activity] using -n option without any active window

### ISSUE THREAD

**Issue by Luka5W** [Luka5W/BashScripts#1]
When moving no window to the next (or probably previous too) activity, the desktop wallpaper of the current activity turns black.

That means anything bad happens…

**Comment by denn-moe** [comment]
first of all: thanks for the script. you really saved my ass.
regarding the problem: i think that is, what avalonvales means when he wrote: sending your desktop to the shadow realm.
this also happens if i have no window selected but try to push it to a specific activity.
i'm new in scripting but i played a bit arround

wnd_focus=$(xdotool getwindowfocus)                                                                                                                         
wnd_title=$(xprop -id $wnd_focus WM_NAME)

kdialog --passivepopup "${wnd_title#*=}" 5

this gives back "Desktop" if no window is selected.
i tried to put it in your moveWindow function and capture it with an elif, but my scripting skills are just too basic...

**Comment by Luka5W** [comment]
Thank you!
I've played around a bit with your code and found another window property; `_NET_WM_WINDOW_TYPE` because I don't want to rely on the window's name.

When executing `sleep 1 && xprop -id $(xdotool getwindowfocus) | grep _NET_WM_WINDOW_TYPE` while the terminal is in foreground, the command prints `_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL`. When I use the 1 second delay to click on the desktop, so the terminal window is not in foreground anymore, the command prints `_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DESKTOP`.

I believe the commit above will fix the bug. What do you think?

Fun fact: When executing `xprop -id $(xdotool getwindowfocus)` (optionally with the `sleep` before) in KDE's konsole it prints out the icon in pixel art (and different sizes). I've tested it with different programs and it just works 🤩

**Comment by denn-moe** [comment]
wow, that was fast...
and works like a charm... 
the wallpaper stays where it belongs.

> Fun fact: When executing xprop -id $(xdotool getwindowfocus) (optionally with the sleep before) in KDE's konsole it prints out the icon in pixel art (and different sizes). I've tested it with different programs and it just works star_struck


that's what i love about kde, the love for the details.

thank you very much and
greetings from the Nordseeküste ;)

**Comment by Luka5W** [comment]
greetings back from hesse btw =)
